version: '2'
services:
  proxy:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 4000:4000/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  freecodecamp-chengdu-fcc-chengdu:
    mem_limit: 104857600
    image: super-frog/documentation:master
    environment:
      PORT: '80'
    stdin_open: true
    tty: true